development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['db_database'] %>
  pool: 5
  host: <%= ENV['db_host'] %>
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>